extends:
 - airbnb
 - import/warnings

parser: babel-eslint

ecmaFeatures:
  experimentalObjectRestSpread: true

rules:
  object-curly-spacing: [2, never]
  no-unused-vars: [2, args: none]
  max-len: [2, 80, 2]
  no-else-return: 0

settings:
  import/parser: babel-eslint
